### ISSUE TITLE
Player names?

### ISSUE THREAD

**Issue by ajbdev** [crorella/hots-parser#24]
Forgive for making this an issue, this is really just a question:

Are the player names parsed out anywhere? Can't seem to find them in either the heroes or teams data dumps but I haven't dug into the units one too much yet.  

If not I'll try to start digging into the parser and figure this out myself.

Really nice work on this by the way, this is a mega huge effort and has been a breeze to work with for a front-end tool I'm working on.

**Comment by crorella** [comment]
Hello @ajbdev, I'm glad you enjoy using the parser :)

The data you want is available in the Players class, the attribute name is "name".
The way it works is like this:
Each hero as a playerId attribute, with that attribute you go to list of players and retrieve the name
```
replayData.players[replayData.heroList[hero].playerId].name
```

Check here for more details: https://github.com/crorella/hots-parser/blob/master/main.py#L32

**Comment by ajbdev** [comment]
Oh, ok - that explains why I wasn't seeing it - I am relying heavily on the data that can be dumped and not using this as a library (instead i'm using it as its own binary using pyinstaller and then using the data that is produced). I will PR to add --dump-players as an option.
