### ISSUE TITLE
ImportError on parser.py

### ISSUE THREAD

**Issue by Dragoncast** [crorella/hots-parser#37]
The parser.py file conflicts with the parser in the standard python library (https://docs.python.org/2/library/parser.html) which results in:

```python
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from parser import processEvents
ImportError: cannot import name processEvents
```
Please rename parser.py to something else to resolve this conflict

**Comment by crorella** [comment]
Thanks for pointing this out @Dragoncast
